# Generated by Django 4.2.3 on 2023-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('release_date', models.TimeField(max_length=50)),
                ('slug', models.SlugField(db_column=models.CharField(max_length=50))),
            ],
        ),
    ]
